module.exports = {
    Admin: require('./Admin.model'),
    Page: require('./Page.model'),
    User: require('./User.model'),
    AdminSettings: require('./Settings.model'),
    State: require('./State.model'),
    EmailNotifcation: require('./EmailNotification.model'),
    Notification: require('./Notification.model'),
    Alert: require('./Alert.model'),
    Setting: require('./Settings.model'),
    AlertType: require('./AlertType.model'),
    Confirm: require('./Confirm.model'),
    Report: require('./Report.model'),
    AdminNotification: require('./AdminNotification.model'),
    Static: require('./Static.model'),
    Health: require('./Health.model'),
    Tracking: require('./Tracking.model'),
    Disalarm: require('./Disalarm.model'),
    VitalRange: require('./VitalRange.model'),
    NoonlightAlert: require('./NoonlightAlert.model'),
    FamilyContact: require('./FamilyContact.model'),

};
